sudo: false
language: python
python:
  - "2.7"
env:
  global:
  - TRAVIS_CACHE_REPO=https://github.com/nimbis/travis-cache-public.git
install:
  - make reqs
script:
  - ./travis-init-script
  - ./.travis-setup/travis-cache-script
  - make pep8
  - make flake8
  - make test
  - make doc
after_success:
  - coveralls
